name: Deploy to GCP

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    name: Doki API Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: murata211guard/doki-backend:latest

#      - name: Generate ENV File
#        env:
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          GOOGLE_API_KEY: ${{ secrets.GCP_API_KEY }}
#          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
#          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
#          JWT_SECRET: ${{ secrets.JWT_SECRET }}
#          CLIENT_HOST_URL: ${{ secrets.CLIENT_HOST_URL }}
#          DB_HOST: ${{ secrets.DB_HOST }}
#          DB_USER: ${{ secrets.DB_USER }}
#          DB_PORT: ${{ secrets.DB_PORT }}
#          DB_DATABASE: ${{ secrets.DB_DATABASE }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#          TZ: ${{ secrets.TZ }}
#        run: |
#          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
#          echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
#          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
#          echo "JWT_SECRET=$JWT_SECRET" >> .env
#          echo "CLIENT_HOST_URL=$CLIENT_HOST_URL" >> .env
#          echo "DB_HOST=$DB_HOST" >> .env
#          echo "DB_USER=$DB_USER" >> .env
#          echo "DB_PORT=$DB_PORT" >> .env
#          echo "DB_DATABASE=$DB_DATABASE" >> .env
#          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
#          echo "TZ=$TZ" >> .env