name: Deploy to GCP

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    name: Doki API Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build Docker Image
        run: |
          touch .env
          echo "${{ secrets.ENV_PRODUCTION }}" >> .env
          cat .env
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/doki-backend:latest .

      - name : Push Docker Image to Docker hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/doki-backend:latest

      - name: SSH into GCP VM and Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.GCP_SSH_KEY }}
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          port: 22
          script: |
            sudo docker ps -a | grep 'murata211guard/doki-backend' | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
            sudo docker run -d -p 8000:8000 murata211guard/doki-backend:latest
            sudo docker ps


          
