name: Deploy to GCP

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    name: Doki API Action
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout Branch
#        uses: actions/checkout@v3
#
#      - name: Generate ENV File
#        env:
#          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
#          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
#          GOOGLE_STORAGE_MEDIA_BUCKET: ${{ secrets.GOOGLE_STORAGE_MEDIA_BUCKET }}
#          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
#          APP_SECRET: ${{ secrets.APP_SECRET }}
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#          DB_PORT: ${{ secrets.DB_PORT }}
#          DB_HOST: ${{ secrets.DB_HOST }}
#          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
#          DB_TYPE: ${{ secrets.DB_TYPE }}
#        run: |
#          echo "GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID" >> .env
#          echo "GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY" >> .env
#          echo "GOOGLE_STORAGE_MEDIA_BUCKET=$GOOGLE_STORAGE_MEDIA_BUCKET" >> .env
#          echo "GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL" >> .env
#          echo "APP_SECRET=$APP_SECRET" >> .env
#          echo "DB_USERNAME=$DB_USERNAME" >> .env
#          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
#          echo "DB_PORT=$DB_PORT" >> .env
#          echo "DB_HOST=$DB_HOST" >> .env
#          echo "DB_SCHEMA=$DB_SCHEMA" >> .env
#          echo "DB_TYPE=$DB_TYPE" >> .env
#
#      - name: Docker Login
#        uses: docker/login-action@v2.0.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Push Container
#        run: |
#          docker build -t murata211guard/doki-backend:latest .
#          docker push murata211guard/doki-backend:latest

      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to GCP
        run: |-
          docker ps -a | grep 'murata211guard/doki-backend:latest' | awk '{print $1}' | xargs --no-run-if-empty docker rm -f
          docker run -d -p 8000:8000 murata211guard/doki-backend:latest


